version: '3.8'

services:

  postgres:
    image: postgres:16-alpine
    container_name: sistema-academico-postgres

    environment:
      POSTGRES_DB: matricula
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: sistema-academico-pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: diego@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234

    ports:
      - "8085:80"

    depends_on:
      - postgres


volumes:

  postgres_data: