spring.application.name=sistema-academico-web

server.port=8081




# JSF
joinfaces.faces-servlet.enabled=true
joinfaces.faces-servlet.url-mappings=*.xhtml


# PrimeFaces
joinfaces.primefaces.theme=saga
joinfaces.primefaces.font-awesome=true


# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


# API Backend
api.url=http://localhost:8080
