spring.application.name=sistema-academico

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/matricula
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
jwt.secret=SistemaAcademicoSecretKey2026SistemaAcademicoSecretKey2026

management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always

management.metrics.tags.application=sistema-academico-backend


